# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.2'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
  deploy:
   runs-on: ubuntu-latest
   needs: build
   steps:
    - name: Deploy to EC2
      env:
        EC2_KEY: ${{ secrets.EC2_PEM }}
      run: |
        echo "${EC2_KEY}" > "test.pem"
        chmod 400 test.pem
        ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -i "test.pem" ubuntu@ec2-13-60-168-15.eu-north-1.compute.amazonaws.com << EOF
          cd unit-testing
          git pull
          go build
          nohup go run main.go > unit-testing/log.out 2>&1 & disown 
          exit
        EOF





