deploy:
  runs-on: ubuntu-latest
  needs: build
  steps:
  - name: Deploy to EC2
    env:
      EC2_KEY: ${{ secrets.EC2_PEM }}
    run: |
      echo "${EC2_KEY}" > "test.pem"
      chmod 400 test.pem
      scp -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -i "test.pem" ./main ubuntu@ec2-13-60-168-15.eu-north-1.compute.amazonaws.com:/home/ubuntu/unit-testing/main

      # Connect to EC2 and create/update the systemd service file
      ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -i "test.pem" ubuntu@ec2-13-60-168-15.eu-north-1.compute.amazonaws.com << EOF
      sudo su -
      cat > /etc/systemd/system/my-go-server.service << 'EOF'
      [Unit]
      Description=My Go Server

      [Service]
      User=ubuntu
      WorkingDirectory=/home/ubuntu/unit-testing
      ExecStart=/home/ubuntu/unit-testing/main

      [Install]
      WantedBy=multi-user.target
      EOF
      systemctl daemon-reload
      systemctl enable my-go-server.service
      systemctl start my-go-server.service
      exit
      EOF